apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
  - name: Postgres Benchmark
    uid: grafana-postgres-benchmark
    type: postgres
    access: proxy
    url: db:5432
    database: ${POSTGRES_DB:-medigenius}
    user: ${POSTGRES_USER:-postgres}
    password: ${POSTGRES_PASSWORD:-postgres}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: false
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
